
.fedora:
    update: &fedora_update
        - dnf update -y
    python: &fedora_python
        - dnf install -y python3-pip


.debian:
    update: &debian_update
        - apt update
    python: &debian_python
        - apt install -y python3-pip
        - python() { command python3 "$@"; }


.fedora.42:
    image: fedora:42
    before_script:
        - *fedora_update
        - *fedora_python

.debian.11:
    image: debian:11
    before_script:
        - *debian_update
        - *debian_python
