
include:
    - project: $CI_PROJECT_ROOT_NAMESPACE/ci-tools
      ref    : $CI_SERVER_FQDN
      file:    [develop.yaml]
      rules:
          - if: $CI_SERVER_FQDN == "gitlab.com"
    #
    - project: $CI_PROJECT_ROOT_NAMESPACE/gramovis/ci-tools
      ref    : $CI_SERVER_FQDN
      file:    [develop.yaml]
      rules:
          - if: $CI_SERVER_FQDN != "gitlab.com"

variables:
    BUILD_DIR: .build


#----------------
.build.core:
#----------------
    extends: [.cit_build_job]
    script:
        - cmake -B ${BUILD_DIR} "-DCMAKE_BUILD_TYPE=${BUILD_CONFIG}" -DBUILD_PARALLEL=1 -DBUILD_TESTING=1 "-DRUNTIME_URL=${RUNTIME_URL}" "-DRUNTIME_REV=${RUNTIME_REV}"
        - cmake --build ${BUILD_DIR} --config ${BUILD_CONFIG} --parallel ${NUMBER_OF_PROCESSORS}
        - pushd ${BUILD_DIR}
        - - ctest --output-on-failure --build-config ${BUILD_CONFIG}
        - popd
    artifacts:
        when: always
        paths:
            - ${BUILD_DIR}/package

#----------------
.build.wheel:
#----------------
    extends: [.cit_build_job, .cit_referenced]
    variables:
        FDEPATH: ${BUILD_DIR}/package/${BUILD_CONFIG}/bin
    script:
        - !reference [.cit_referenced, script]
        - python -m pip wheel -w dist .
        - auditwheel ${FDEPATH} repair dist/fde-*.whl -w .dist
        - rm dist/fde-*.whl  #< delete incomplete wheel
        - cp -r .dist/* dist #< before copying repaired one into dist
        - mv dist "${PACKAGE_DIR}.${PLATFORM_NAME}"

#----------------
.test.wheel:
#----------------
    extends: [.cit_test_job]
    script:
        - pip install --find-links=${PACKAGE_DIR}.${PLATFORM_NAME} fde pytest
        - cd test #           . o O (avoid including fde-module from source directories!)
        - - pytest --rootdir=. -s --log-cli-level=DEBUG test_0_basic.py
    variables:
        PYTHON_VERSION: 3.11



#---------------
# debian:11
#---

core.debian:
    extends: [.build.core, .runner.debian.compiler:11]

wheel.debian:
    extends: [.build.wheel, .runner.debian.compiler:11]
    needs:   [core.debian]
    before_script:
        - !reference [.debian, before_script]
        - !reference [.tools.debian, install, python.auditwheel]

test.debian:
    extends: [.test.wheel, .runner.debian:11]
    needs:   [wheel.debian]
    before_script:
        - !reference [.debian, before_script]
        - !reference [.tools.debian, setup, conda.python]


#---------------
# windows
#---

core.windows:
    extends: [.build.core, .runner.windows.compiler:2025]
    variables:
        RUNTIME_URL: $AC2_RUNTIME_URL
        RUNTIME_REV: $AC2_RUNTIME_REV

wheel.windows:
    extends: [.build.wheel, .runner.windows.compiler:2025]
    needs:   [core.windows]
    before_script:
        - !reference [.windows, before_script]
        - !reference [.tools.windows, install, python.auditwheel]

test.windows:
    extends: [.test.wheel, .runner.windows.core:2025]
    needs:   [wheel.windows]
    before_script:
        - !reference [.windows, before_script]
        - !reference [.tools.windows, setup, conda.python]


#---------------
# all platforms
#---

wheel:
    extends: [.cit_build_job, .cit_job_collect]
    needs:   [wheel.debian, wheel.windows]


#---------------
# external
#---

#-------------------------
test.athlet-controller:
#-------------------------
    stage: test
    needs: [wheel]
    trigger:
        project: grs/gramovis/athlet-controller
        branch: master
        strategy: mirror
    variables:
        FDE_UPSTREAM: ${wheel_JOB_IDs}


#-----------------------
pack:
#-----------------------
    extends: [.cit_pack_job]
    needs:   [test.debian, test.windows, wheel.debian, wheel.windows]
    script:
        # pack packages zipped with its dependencies...
        - !reference [.cit_pack_job, script]
        # ...  and simply the fde-*.whl files for all platforms.
        - cp -n ${PACKAGE_DIR}.*/fde-*.whl ${PACKAGE_DIR}
    variables:
        PACKED_PLATFORM_NAMES: debian windows

#-----------------------
upload:
#-----------------------
    extends: .cit_upload
    needs:   [pack]

#-----------------------
publish:
#-----------------------
    extends: .cit_publish
    needs:   [upload]
