stages:
  - build

linux:
  stage: build
  tags:
    - docker
    - linux
  image: fedora:33
  before_script:
    - dnf install -y g++ gcc-gfortran cmake gcovr python3-pip

  script:
    - mkdir -p _build
    - cd _build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=1 -DCMAKE_Fortran_FLAGS=--coverage -DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_FLAGS=--coverage ..
    - make
    - make test
    - mkdir -p ../coverage
    - gcovr -r .. src libfortres
    - gcovr -r .. src libfortres --xml=../coverage.xml --html-details=../coverage/coverage.html
    - cd ..
    - python3 -m pip install wheel
    - FDEPATH=_build/package/Debug/bin python3 setup.py bdist_wheel --dist-dir coverage
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expose_as: 'Coverage Report'
    paths:
      - coverage/
      #- dist/*.whl


