
include:
    - project: grs/gramovis/ci-tools
      ref:     main
      file:    [develop.yaml, tools.yaml]


#----------------
.build.core:
#----------------
    extends: [.cit_build_job]
    script:
        - cmake -B ${BUILD_DIR} ${CONFIG_FLAGS}
        - cmake --build ${BUILD_DIR} --config ${BUILD_CONFIG} --parallel ${NUMBER_OF_PROCESSORS}
        - ctest --output-on-failure  --test-dir ${BUILD_DIR} --build-config ${BUILD_CONFIG}
    variables:
        BUILD_DIR:    .build
        CONFIG_FLAGS: -DBUILD_TESTING=1 -DCMAKE_BUILD_TYPE=${BUILD_CONFIG} -DBUILD_PARALLEL=1
    artifacts:
        when: always
        paths:
            - ${BUILD_DIR}/package

#----------------
.build.wheel:
#----------------
    extends: [.cit_build_job]
    script:
        - pip wheel . -w dist
        - auditwheel ${FDEPATH} repair dist/fde-*.whl
    variables:
        FDEPATH: .build/package/${BUILD_CONFIG}/bin
    artifacts:
        paths:
            - wheelhouse

#----------------
.test.wheel:
#----------------
    extends: [.cit_test_job]
    script:
        - pip install --find-links=wheelhouse fde
        - cd test
        - python test_wheel_setup.py


#----------------
# build stage
#----

core.linux:
    extends: [.build.core, .image.debian.compiler:2025]

core.windows:
    extends: [.build.core, .image.windows.compiler:2025]


wheel.linux:
    extends: [.build.wheel, .image.debian.compiler:2025]
    needs:
        - job: core.linux
          artifacts: true
    before_script:
        - !reference [.tools.linux, install, python.auditwheel]

wheel.windows:
    extends: [.build.wheel, .image.windows.compiler:2025]
    needs:
        - job: core.windows
          artifacts: true
    before_script:
        - !reference [.tools.windows, install, python.auditwheel]


#----------------
# test stage
#----

test.wheel.linux:
    extends: [.test.wheel, .image.debian.core:2025]
    needs:
        - job: wheel.linux
          artifacts: true
    before_script:
        - !reference [.tools.linux, install, python.venv]

test.wheel.windows:
    extends: [.test.wheel, .image.windows.core:2025]
    needs:
        - job: wheel.windows
          artifacts: true
    before_script:
        - !reference [.tools.windows, install, python.venv]
